### ISSUE TITLE
[SPIKE] Store user specific info

### ISSUE THREAD

**Issue by JClutch** [Jabroni-Tech/text-extension#12]
Store user specific info via the built in data storage

Investigate initial setup

Open Questions -

Q.) Is the data stored locally per session or is it by user based profiles?

**Comment by pengcheng95** [comment]
Q) What type of storage are they using? (key value, graph, etc)

**Comment by JClutch** [comment]
Not going to do a formal doc write up (cause I'm lazy and this seems simpler than anticipated)

https://stackoverflow.com/questions/5364062/how-can-i-save-information-locally-in-my-chrome-extension
https://developer.chrome.com/extensions/storage
https://developer.chrome.com/extensions/storage#type-StorageArea

Key takeaways
-permissions need to add storage
-can access storage from all content scripts
-not encrypted but stores info by user
-has onChanged event listeners
