### ISSUE TITLE
Text-Extension Trigger - Idea Generation

### ISSUE THREAD

**Issue by JClutch** [Jabroni-Tech/text-extension#5]
Leave comments with ideas for how to trigger the text-extensions (v0 and future iterations)

**Comment by JClutch** [comment]
Right Click Menu
Highlight + Keyboard Command when highlighted
On Highlighting

**Comment by pengcheng95** [comment]
Highlight  + Right click menu

**Comment by JClutch** [comment]
First trigger will be highlight + right click menu
